// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdL0F87NLmM-bFoNo7M248KdKZwOhqL1k',
    appId: '1:651925053245:web:71aa6c08410c3de43daf54',
    messagingSenderId: '651925053245',
    projectId: 'ohmypet-47930',
    authDomain: 'ohmypet-47930.firebaseapp.com',
    databaseURL: 'https://ohmypet-47930-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ohmypet-47930.appspot.com',
    measurementId: 'G-GSXCXTSV2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB70WLE_D28-apEMdRZkWZ6SPfhBmqQqb0',
    appId: '1:651925053245:android:8b62b8dbc48665e43daf54',
    messagingSenderId: '651925053245',
    projectId: 'ohmypet-47930',
    databaseURL: 'https://ohmypet-47930-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ohmypet-47930.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD07HrkU1l_BqBFIQUtGt10fChejEx_Mo',
    appId: '1:651925053245:ios:c1a1442507ffd20a3daf54',
    messagingSenderId: '651925053245',
    projectId: 'ohmypet-47930',
    databaseURL: 'https://ohmypet-47930-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ohmypet-47930.appspot.com',
    iosClientId: '651925053245-f83cpb2lr5grupqcbq780fu1dkplr789.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohmypet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD07HrkU1l_BqBFIQUtGt10fChejEx_Mo',
    appId: '1:651925053245:ios:c1a1442507ffd20a3daf54',
    messagingSenderId: '651925053245',
    projectId: 'ohmypet-47930',
    databaseURL: 'https://ohmypet-47930-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ohmypet-47930.appspot.com',
    iosClientId: '651925053245-f83cpb2lr5grupqcbq780fu1dkplr789.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohmypet',
  );
}
